export const MODULES = [
  { key: "dashboard", label: "Dashboard" },
  { key: "produits", label: "Produits" },
  { key: "fournisseurs", label: "Fournisseurs" },
  { key: "factures", label: "Factures" },
  { key: "receptions", label: "Réceptions" },
  { key: "inventaires", label: "Inventaires" },
  { key: "mouvements", label: "Mouvements" },
  { key: "pertes", label: "Pertes" },
  { key: "fiches", label: "Fiches" },
  { key: "menus", label: "Menus" },
  { key: "carte", label: "Carte" },
  { key: "recettes", label: "Recettes" },
  { key: "requisitions", label: "Réquisitions" },
  { key: "promotions", label: "Promotions" },
  { key: "notifications", label: "Notifications" },
  { key: "documents", label: "Documents" },
  { key: "planning", label: "Planning" },
  { key: "analyse", label: "Analyse" },
  { key: "reporting", label: "Reporting" },
  { key: "stats", label: "Stats" },
  { key: "alertes", label: "Alertes" },
  { key: "taches", label: "Tâches" },
  { key: "transferts", label: "Transferts" },
  { key: "signalements", label: "Signalements" },
  { key: "validations", label: "Validations" },
  { key: "journal", label: "Journal" },
  { key: "audit", label: "Audit" },
  { key: "utilisateurs", label: "Utilisateurs" },
  { key: "roles", label: "Rôles" },
  { key: "mamas", label: "Mamas" },
  { key: "permissions", label: "Permissions" },
  { key: "access", label: "Accès" },
  { key: "api_keys", label: "Clés API" },
  { key: "aide", label: "Aide" },
  { key: "settings", label: "Paramètres" }
];
