export const MODULES = [
  { label: "Dashboard", key: "dashboard" },
  { label: "Produits", key: "produits" },
  { label: "Fournisseurs", key: "fournisseurs" },
  { label: "Factures", key: "factures" },
  { label: "Réceptions", key: "receptions" },
  { label: "Inventaires", key: "inventaires" },
  { label: "Menus", key: "menus" },
  { label: "Carte", key: "carte" },
  { label: "Recettes", key: "recettes" },
  { label: "Réquisitions", key: "requisitions" },
  { label: "Promotions", key: "promotions" },
  { label: "Notifications", key: "notifications" },
  { label: "Documents", key: "documents" },
  { label: "Planning", key: "planning" },
  { label: "Tâches", key: "taches" },
  { label: "Alertes", key: "alertes" },
  { label: "Analyse", key: "analyse" },
  { label: "Reporting", key: "reporting" },
  { label: "Utilisateurs", key: "utilisateurs" },
  { label: "Rôles", key: "roles" },
  { label: "Mamas", key: "mamas" },
  { label: "Permissions", key: "permissions" },
  { label: "Paramètres", key: "settings" },
  { label: "API Keys", key: "apikeys" },
  { label: "Accès", key: "access" },
  { label: "Aide", key: "aide" },
  { label: "Achats", key: "achats" },
  { label: "Bons de livraison", key: "bons_livraison" },
  { label: "Planning Prévisionnel", key: "planning_previsionnel" },
  { label: "Fiches techniques", key: "fiches_techniques" },
  { label: "Stats", key: "stats" },
  { label: "Consolidation", key: "consolidation" },
  { label: "Menu Engineering", key: "menu_engineering" },
  { label: "Zones de stock", key: "zones_stock" },
  { label: "Licences", key: "licences" },
  { label: "Paramétrage", key: "parametrage" },
  { label: "Feedback", key: "feedback" },
  { label: "Logs", key: "logs" },
];
