import {
  Home,
  Boxes,
  FileText,
  ChefHat,
  Menu as MenuIcon,
  Calendar,
  Settings,
  Truck,
  Package,
  BookOpen,
  BarChart,
  BarChart2,
  TrendingUp,
  AlertTriangle,
  ClipboardList,
  FilePlus,
  ArrowLeftRight,
  Users,
} from 'lucide-react';
import lazyWithPreload from '@/lib/lazyWithPreload';

export const MODULES = [
  {
    path: '/dashboard',
    element: lazyWithPreload(() => import('@/pages/Dashboard.jsx')),
    labelKey: 'nav.dashboard',
    icon: Home,
    rightKey: 'dashboard',
    showInSidebar: true,
  },
  {
    path: '/produits',
    element: lazyWithPreload(() => import('@/pages/produits/Produits.jsx')),
    labelKey: 'nav.produits',
    icon: Boxes,
    rightKey: 'produits',
    showInSidebar: true,
  },
  {
    path: '/fournisseurs',
    element: lazyWithPreload(() => import('@/pages/fournisseurs/Fournisseurs.jsx')),
    labelKey: 'nav.fournisseurs',
    icon: Truck,
    rightKey: 'fournisseurs',
    showInSidebar: true,
  },
  {
    path: '/factures',
    element: lazyWithPreload(() => import('@/pages/factures/Factures.jsx')),
    labelKey: 'nav.factures',
    icon: FileText,
    rightKey: 'factures',
    showInSidebar: true,
  },
  {
    path: '/fiches',
    element: lazyWithPreload(() => import('@/pages/fiches/Fiches.jsx')),
    labelKey: 'nav.fiches',
    icon: ChefHat,
    rightKey: 'fiches_techniques',
    showInSidebar: true,
  },
  {
    path: '/menus',
    element: lazyWithPreload(() => import('@/pages/menus/Menus.jsx')),
    labelKey: 'nav.menus',
    icon: MenuIcon,
    rightKey: 'menus',
    showInSidebar: true,
  },
  {
    path: '/menu',
    element: lazyWithPreload(() => import('@/pages/menu/MenuDuJour.jsx')),
    labelKey: 'nav.menuDuJour',
    icon: Calendar,
    rightKey: 'menu_du_jour',
    showInSidebar: true,
  },
  {
    path: '/receptions',
    element: lazyWithPreload(() => import('@/pages/receptions/Receptions.jsx')),
    labelKey: 'nav.receptions',
    icon: Package,
    rightKey: 'receptions',
    showInSidebar: true,
  },
  {
    path: '/recettes',
    element: lazyWithPreload(() => import('@/pages/recettes/Recettes.jsx')),
    labelKey: 'nav.recettes',
    icon: BookOpen,
    rightKey: 'recettes',
    showInSidebar: true,
  },
  {
    path: '/tableaux-de-bord',
    element: lazyWithPreload(() => import('@/pages/analyse/TableauxDeBord.jsx')),
    labelKey: 'nav.tableauxDeBord',
    icon: BarChart,
    rightKey: 'analyse',
    showInSidebar: true,
  },
  {
    path: '/comparatif',
    element: lazyWithPreload(() => import('@/pages/analyse/Analyse.jsx')),
    labelKey: 'nav.comparatif',
    icon: BarChart2,
    rightKey: 'analyse',
    showInSidebar: true,
  },
  {
    path: '/surcouts',
    element: lazyWithPreload(() => import('@/pages/surcouts/Surcouts.jsx')),
    labelKey: 'nav.surcouts',
    icon: TrendingUp,
    rightKey: 'analyse',
    showInSidebar: true,
  },
  {
    path: '/stock/alertes',
    element: lazyWithPreload(() => import('@/pages/stock/AlertesRupture.jsx')),
    labelKey: 'nav.alertesRupture',
    icon: AlertTriangle,
    rightKey: 'alertes',
    showInSidebar: true,
  },
  {
    path: '/stock/inventaire',
    element: lazyWithPreload(() => import('@/pages/stock/Inventaire.jsx')),
    labelKey: 'nav.inventaire',
    icon: ClipboardList,
    rightKey: 'inventaires',
    showInSidebar: true,
  },
  {
    path: '/requisitions',
    element: lazyWithPreload(() => import('@/pages/requisitions/Requisitions.jsx')),
    labelKey: 'nav.requisitions',
    icon: FilePlus,
    rightKey: 'requisitions',
    showInSidebar: true,
  },
  {
    path: '/stock/transferts',
    element: lazyWithPreload(() => import('@/pages/stock/Transferts.jsx')),
    labelKey: 'nav.transferts',
    icon: ArrowLeftRight,
    rightKey: 'mouvements',
    showInSidebar: true,
  },
  {
    path: '/parametrage/zones',
    element: lazyWithPreload(() => import('@/pages/parametrage/Zones.jsx')),
    labelKey: 'nav.zones',
    icon: Settings,
    rightKey: 'zones_stock',
    showInSidebar: true,
  },
  {
    path: '/parametrage/familles',
    element: lazyWithPreload(() => import('@/pages/parametrage/Familles.jsx')),
    labelKey: 'nav.familles',
    icon: Boxes,
    rightKey: 'parametrage',
    showInSidebar: true,
  },
  {
    path: '/parametrage/sous-familles',
    element: lazyWithPreload(() => import('@/pages/parametrage/SousFamilles.jsx')),
    labelKey: 'nav.sousFamilles',
    icon: Boxes,
    rightKey: 'parametrage',
    showInSidebar: true,
  },
  {
    path: '/parametrage/unites',
    element: lazyWithPreload(() => import('@/pages/parametrage/Unites.jsx')),
    labelKey: 'nav.unites',
    icon: Boxes,
    rightKey: 'parametrage',
    showInSidebar: true,
  },
  {
    path: '/parametrage/utilisateurs',
    element: lazyWithPreload(() => import('@/pages/parametrage/Utilisateurs.jsx')),
    labelKey: 'nav.utilisateurs',
    icon: Users,
    rightKey: 'utilisateurs',
    showInSidebar: true,
  },
];

export default MODULES;
