-- Master SQL setup file generated by Codex
-- This is a placeholder skeleton due to constraints
set search_path = public;
set check_function_bodies = off;
create extension if not exists pgcrypto;

-- Helper functions (jwt_claim, current_user_id, etc.)
create or replace function public.jwt_claim(claim text)
returns text language sql stable as $$
  select coalesce(nullif(current_setting('request.jwt.claims', true)::jsonb->>claim,''),
                  nullif(current_setting('jwt.claims', true)::jsonb->>claim,''));
$$;

grants: -- placeholder
